#ifndef __org_openoffice_vba_Excel_Constants_idl__
#define __org_openoffice_vba_Excel_Constants_idl__
module org  { module openoffice { module vba { module Excel { 

constants Constants
{
const long xlAll = -4104; //(&HFFFFEFF8)
const short xlFirst = 0;
const short xlLast = 1;
const long xlNone = -4142; //(&HFFFFEFD2)
};
}; }; }; };

#endif
