#ifndef __org_openoffice_excel_Constants_idl__
#define __org_openoffice_excel_Constants_idl__
module org  { module openoffice { module excel { 

constants Constants
{
const long xlNone = -4142; //(&HFFFFEFD2)
const long xlAll = -4104; //(&HFFFFEFF8)
const long xlAutomatic = -4105; // (&HFFFFEFF7)

};
}; }; };

#endif
