#ifndef __org_openoffice_excel_XChartObject_idl__
#define __org_openoffice_excel_XChartObject_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif
#ifndef __org_openoffice_vba_XHelperInterface_idl__
#include <org/openoffice/vba/XHelperInterface.idl>
#endif
//=============================================================================

module org {  module openoffice {  module excel { 

//=============================================================================
interface XChart;
interface XChartObject
{
	interface ::org::openoffice::vba::XHelperInterface;

	[attribute, readonly] XChart Chart;
	[attribute, readonly] string Name;
	any test();
};

//=============================================================================

}; }; };

#endif


