#ifndef __org_openoffice_excel_XCharacters_idl__
#define __org_openoffice_excel_XCharacters_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif
#ifndef __org_openoffice_excel_XFont_idl__
#include <org/openoffice/excel/XFont.idl>
#endif
#ifndef __org_openoffice_vba_XHelperInterface_idl__
#include <org/openoffice/vba/XHelperInterface.idl>
#endif
//=============================================================================

module org {  module openoffice {  module excel { 

//=============================================================================
interface XCharacters
{
	interface ::org::openoffice::vba::XHelperInterface;

	[attribute] string Caption;
	[attribute, readonly ] long Count;
	[attribute] string Text;
	[attribute] XFont Font;
	void Insert([in] string String);
	void Delete();
};

//=============================================================================

}; }; };

#endif


