#ifndef __org_openoffice_vba_Excel_XlCalculationInterruptKey_idl__
#define __org_openoffice_vba_Excel_XlCalculationInterruptKey_idl__
module org  { module openoffice { module vba { module Excel {

constants XlCalculationInterruptKey
{
        const short xlAnyKey = 2;
        const short xlEscKey = 1;
        const short xlNoKey = 0;
};
}; }; }; };
#endif
