#ifndef __org_openoffice_excel_XlCellInsertionMode_idl__
#define __org_openoffice_excel_XlCellInsertionMode_idl__
module org  { module openoffice { module excel {

constants XlCellInsertionMode
{
        const short xlInsertDeleteCells = 1;
        const short xlInsertEntireRows = 2;
        const short xlOverwriteCells = 0;
};
}; }; };
#endif
