#ifndef __org_openoffice_vba_Excel_XlChartSplitType_idl__
#define __org_openoffice_vba_Excel_XlChartSplitType_idl__
module org  { module openoffice { module vba { module Excel {

constants XlChartSplitType
{
        const short xlSplitByCustomSplit = 4;
        const short xlSplitByPercentValue = 3;
        const short xlSplitByPercentPosition = 1;
        const short xlSplitByValue = 2;
};
}; }; }; };
#endif
