#ifndef __org_openoffice_excel_XlColorIndex_idl__
#define __org_openoffice_excel_XlColorIndex_idl__
module org  { module openoffice { module excel {

constants XlColorIndex
{
        const long xlColorIndexAutomatic = -4105; //(&HFFFFEFF7) 
        const long xlColorIndexNone = -4142; //(&HFFFFEFD2)
};
}; }; };
#endif
