#ifndef __org_openoffice_vba_Excel_XlCutCopyMode_idl__
#define __org_openoffice_vba_Excel_XlCutCopyMode_idl__
module org  { module openoffice { module vba { module Excel { 

constants XlCutCopyMode
{
const long xlCopy = 1;
const long xlCut = 2;
};
}; }; }; };

#endif
