#ifndef __org_openoffice_vba_Excel_XlDataLabelSeparator_idl__
#define __org_openoffice_vba_Excel_XlDataLabelSeparator_idl__
module org  { module openoffice { module vba { module Excel {

constants XlDataLabelSeparator
{
        const short xlDataLabelSeparatorDefault = 1;
};
}; }; }; };
#endif
