#ifndef __org_openoffice_vba_Excel_XlFilterAction_idl__
#define __org_openoffice_vba_Excel_XlFilterAction_idl__
module org  { module openoffice { module vba { module Excel {

constants XlFilterAction
{
        const short xlFilterCopy = 2;
        const short xlFilterInPlace = 1;
};
}; }; }; };
#endif
