#ifndef __org_openoffice_excel_XlFilterAction_idl__
#define __org_openoffice_excel_XlFilterAction_idl__
module org  { module openoffice { module excel {

constants XlFilterAction
{
        const short xlFilterCopy = 2;
        const short xlFilterInPlace = 1;
};
}; }; };
#endif
