#ifndef __org_openoffice_vba_Excel_XlFormatConditionType_idl__
#define __org_openoffice_vba_Excel_XlFormatConditionType_idl__
module org  { module openoffice { module vba { module Excel {

constants XlFormatConditionType
{
        const short xlCellValue = 1;
        const short xlExpression = 2;
};
}; }; }; };
#endif
