#ifndef __org_openoffice_excel_XlLinkInfo_idl__
#define __org_openoffice_excel_XlLinkInfo_idl__
module org  { module openoffice { module excel {

constants XlLinkInfo
{
        const short xlEditionDate = 2;
        const short xlLinkInfoStatus = 3;
        const short xlUpdateState = 1;
};
}; }; };
#endif
