#ifndef __org_openoffice_vba_Excel_XlLookAt_idl__
#define __org_openoffice_vba_Excel_XlLookAt_idl__

module org  { module openoffice { module vba { module Excel { 

constants XlLookAt
{
	const short xlPart = 2;
	const short xlWhole = 1;
};
}; }; }; };
#endif
