#ifndef __org_openoffice_excel_XlLookAt_idl__
#define __org_openoffice_excel_XlLookAt_idl__
module org  { module openoffice { module excel {

constants XlLookAt
{
        const short xlPart = 2;
        const short xlWhole = 1;
};
}; }; };
#endif
