#ifndef __org_openoffice_excel_XlMsoZOrderCmd_idl__
#define __org_openoffice_excel_XlMsoZOrderCmd_idl__
module org { module openoffice { module excel {

constants XlMsoZOrderCmd
{
    const long msoBringToFront = 0;
    const long msoSendToBack = 1;
    const long msoBringForward = 2;
    const long msoSendBackward =3;
    const long msoBringInFrontOfText = 4;
    const long msoSendBehindText = 5;
};

}; }; };
#endif
