#ifndef __org_openoffice_excel_XlObjectSize_idl__
#define __org_openoffice_excel_XlObjectSize_idl__
module org  { module openoffice { module excel {

constants XlObjectSize
{
        const short xlFitToPage = 2;
        const short xlFullPage = 3;
        const short xlScreenSize = 1;
};
}; }; };
#endif
