#ifndef __org_openoffice_vba_Excel_XlObjectSize_idl__
#define __org_openoffice_vba_Excel_XlObjectSize_idl__
module org  { module openoffice { module vba { module Excel {

constants XlObjectSize
{
        const short xlFitToPage = 2;
        const short xlFullPage = 3;
        const short xlScreenSize = 1;
};
}; }; }; };
#endif
