#ifndef __org_openoffice_vba_Excel_XlOLEVerb_idl__
#define __org_openoffice_vba_Excel_XlOLEVerb_idl__
module org  { module openoffice { module vba { module Excel {

constants XlOLEVerb
{
        const short XlVerbOpen = 2;
        const short XlVerbPrimary = 1;
};
}; }; }; };
#endif
