#ifndef __org_openoffice_excel_XlPageOrientation_idl__
#define __org_openoffice_excel_XlPageOrientation_idl__
module org  { module openoffice { module excel {

constants XlPageOrientation
{
        const short xlLandscape = 2;
        const short xlPortrait = 1;
};
}; }; };
#endif
