#ifndef __org_openoffice_vba_Excel_XlPasteSpecialOperation_idl__
#define __org_openoffice_vba_Excel_XlPasteSpecialOperation_idl__
module org  { module openoffice { module vba { module Excel {

constants XlPasteSpecialOperation
{
        const long xlPasteSpecialOperationAdd = 2;
        const long xlPasteSpecialOperationDivide = 5;
        const long xlPasteSpecialOperationMultiply = 4;
        const long xlPasteSpecialOperationNone = -4142; //(&HFFFFEFD2)
        const long xlPasteSpecialOperationSubstract = 3;
};
}; }; }; };
#endif
