#ifndef __org_openoffice_excel_XlPasteSpecialOperation_idl__
#define __org_openoffice_excel_XlPasteSpecialOperation_idl__
module org  { module openoffice { module excel {

constants XlPasteSpecialOperation
{
        const long xlPasteSpecialOperationAdd = 2;
        const long xlPasteSpecialOperationDivide = 5;
        const long xlPasteSpecialOperationMultiply = 4;
        const long xlPasteSpecialOperationNone = -4142; //(&HFFFFEFD2)
        const long xlPasteSpecialOperationSubtract = 3;
};
}; }; };
#endif
