#ifndef __org_openoffice_excel_XlPivotTableVersionList_idl__
#define __org_openoffice_excel_XlPivotTableVersionList_idl__
module org  { module openoffice { module excel {

constants XlPivotTableVersionList
{
        const long xlPivotTableVersion10 = 1;
        const long xlPivotTableVersion2000 = 0;
        const long xlPivotTableCurrent = -1; //(&HFFFFFFFF)
};
}; }; };
#endif
