#ifndef __org_openoffice_vba_Excel_XlPlacement_idl__
#define __org_openoffice_vba_Excel_XlPlacement_idl__
module org  { module openoffice { module vba { module Excel {

constants XlPlacement
{
        const short xlFreeFloating = 3;
        const short xlMove = 2;
        const short xlMoveAndSize = 1;
};
}; }; }; };
#endif
