#ifndef __org_openoffice_excel_XlQueryType_idl__
#define __org_openoffice_excel_XlQueryType_idl__
module org  { module openoffice { module excel {

constants XlQueryType
{
        const short xlADORecordset = 7;
        const short xlDAORecordset = 2;
        const short xlODBCQuery = 1;
        const short xlOLEDBQuery = 5;
        const short xlTextImport = 6;
        const short xlWebQuery = 4;
};
}; }; };
#endif
