#ifndef __org_openoffice_excel_XlRobustConnect_idl__
#define __org_openoffice_excel_XlRobustConnect_idl__
module org  { module openoffice { module excel {

constants XlRobustConnect
{
        const short xlAlways = 1;
        const short xlAsRequired = 0;
        const short xlNever = 2;
};
}; }; };
#endif
