#ifndef __org_openoffice_excel_XlRunAutoMacro_idl__
#define __org_openoffice_excel_XlRunAutoMacro_idl__
module org  { module openoffice { module excel {

constants XlRunAutoMacro
{
        const short xlAutoActivate = 3;
        const short xlAutoClose = 2;
        const short xlAutoDeactivate = 4;
        const short xlAutoOpen = 1;
};
}; }; };
#endif
