#ifndef __org_openoffice_excel_XlSearchWithin_idl__
#define __org_openoffice_excel_XlSearchWithin_idl__
module org  { module openoffice { module excel {

constants XlSearchWithin
{
        const short xlWithinSheet = 1;
        const short xlWithinWorkbook = 2;
};
}; }; };
#endif
