#ifndef __org_openoffice_excel_XlSheetVisibility_idl__
#define __org_openoffice_excel_XlSheetVisibility_idl__
module org  { module openoffice { module excel {

constants XlSheetVisibility
{
        const long xlSheetHidden = 0;
        const long xlSheetVeryHidden = 2;
        const long xlSheetVisible = -1; //(&HFFFFFFFF)
};
}; }; };
#endif
