#ifndef __org_openoffice_vba_Excel_XlSortDataOption_idl__
#define __org_openoffice_vba_Excel_XlSortDataOption_idl__
module org  { module openoffice { module vba { module Excel { 

constants XlSortDataOption
{
const short xlSortTextAsNumbers = 1;
const short xlSortNormal = 1;
};
}; }; }; };

#endif
