#ifndef __org_openoffice_vba_Excel_XlSortMethod_idl__
#define __org_openoffice_vba_Excel_XlSortMethod_idl__

module org  { module openoffice { module vba { module Excel { 
constants XlSortMethod
{
	const short xlPinYin = 1;
	const short xlStroke = 2;

};
}; }; }; };
#endif
