#ifndef __org_openoffice_excel_XlSortType_idl__
#define __org_openoffice_excel_XlSortType_idl__
module org  { module openoffice { module excel {

constants XlSortType
{
        const short xlSortLabels = 2;
        const short xlSortValues = 1;
};
}; }; };
#endif
