#ifndef __org_openoffice_excel_XlSpeakDirection_idl__
#define __org_openoffice_excel_XlSpeakDirection_idl__
module org  { module openoffice { module excel {

constants XlSpeakDirection
{
        const short xlSpeakByColumns = 1;
        const short xlSpeakByRows = 0;
};
}; }; };
#endif
