#ifndef __org_openoffice_excel_XlTabPosition_idl__
#define __org_openoffice_excel_XlTabPosition_idl__
module org  { module openoffice { module excel {

constants XlTabPosition
{
        const short xlTabPositionFirst = 0;
        const short xlTabPositionLast = 1;
};
}; }; };
#endif
