#ifndef __org_openoffice_excel_XlTextParsingType_idl__
#define __org_openoffice_excel_XlTextParsingType_idl__
module org  { module openoffice { module excel {

constants XlTextParsingType
{
        const short xlDelimited = 1;
        const short xlFixedWidth = 2;
};
}; }; };
#endif
