#ifndef __org_openoffice_excel_XlUpdateLinks_idl__
#define __org_openoffice_excel_XlUpdateLinks_idl__
module org  { module openoffice { module excel {

constants XlUpdateLinks
{
        const short XlUpdateLinksAlways = 3;
        const short XlUpdateLinksNever = 2;
        const short XlUpdateLinksUserSetting = 1;
};
}; }; };
#endif
