#ifndef __org_openoffice_vba_Excel_XlUpdateLinks_idl__
#define __org_openoffice_vba_Excel_XlUpdateLinks_idl__
module org  { module openoffice { module vba { module Excel {

constants XlUpdateLinks
{
        const short XlUpdateLinksAlways = 3;
        const short XlUpdateLinksNever = 2;
        const short XlUpdateLinksUserSetting = 1;
};
}; }; }; };
#endif
