#ifndef __org_openoffice_excel_XlWindowView_idl__
#define __org_openoffice_excel_XlWindowView_idl__
module org  { module openoffice { module excel {
constants XlWindowView
{
        const short xlNormalView = 1;
        const short xlPageBreakPreview = 2;
};
}; }; };
#endif
