#ifndef __org_openoffice_vba_Excel_XlXmlExportResult_idl__
#define __org_openoffice_vba_Excel_XlXmlExportResult_idl__
module org  { module openoffice { module vba { module Excel {
constants XlXmlExportResult
{
        const short xlXmlExportSuccess = 0;
        const short xlXmlExportValidationFailed = 1;
};
}; }; }; };
#endif
