#ifndef __org_openoffice_excel_XlYesNoGuess_idl__
#define __org_openoffice_excel_XlYesNoGuess_idl__

module org  { module openoffice { module excel { 
constants XlYesNoGuess
{
	const short xlGuess = 0;
	const short xlNo = 2;
	const short xlYes = 1;
};
}; }; };
#endif
