#ifndef __org_openoffice_excel_XPivotTables_idl__
#define __org_openoffice_excel_XPivotTables_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

#ifndef __org_openoffice_vba_XCollection_idl__
#include <org/openoffice/vba/XCollection.idl>
#endif

//=============================================================================

module org {  module openoffice {  module excel { 

//=============================================================================
interface XPivotTables
{

	interface org::openoffice::vba::XCollection;
	// PivotCache should be a PivotCache object ( but thats not defined
	// yet )
	//XPivotTable Add( [in] any PivotCache, [in] any TableDestination, [in] any TableName, [in] any ReadData );
	
};

//=============================================================================

}; }; };

#endif


