#ifndef __org_openoffice_excel_XTextFrame_idl__
#define __org_openoffice_excel_XTextFrame_idl__

#ifndef __org_openoffice_vba_XHelperInterface_idl__
#include <org/openoffice/vba/XHelperInterface.idl>
#endif

#ifndef __org_openoffice_excel_XCharacters_idl__
#include <org/openoffice/excel/XCharacters.idl>
#endif

module org {  module openoffice {  module excel {
interface XTextFrame : org::openoffice::vba::XHelperInterface
{
    [attribute] boolean AutoSize;
    [attribute] float MarginBottom;
    [attribute] float MarginTop;
    [attribute] float MarginLeft;
    [attribute] float MarginRight;
    XCharacters Characters();
    /*I don't find it in msdn
    Range TextRange();*/
};
}; }; };
#endif//__org_openoffice_excel_XTextFrame_idl__
