#ifndef __org_openoffice_excel_XWindows_idl__
#define __org_openoffice_excel_XWindows_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

#ifndef __org_openoffice_vba_XCollection_idl__
#include <org/openoffice/vba/XCollection.idl>
#endif

//=============================================================================

module org {  module openoffice {  module excel { 

//=============================================================================
interface XWindows
{
	interface ::org::openoffice::vba::XCollection;

	void Arrange( [in] long ArrangeStyle, [in] any ActiveWorkbook, [in] any SyncHorizontal, [in] any SyncVertical );	
};

//=============================================================================

}; }; };

#endif


