#!/usr/bin/perl -w

$SRC_URL='http://ooo.ximian.com/packages';

$WGET='/usr/bin/wget';

if (!-d "src") {
    `mkdir -p src`;
}

if (@ARGV > 0) {
    $tag = shift (@ARGV);
} else {
    $tag = `bin/latest-patchset patches`;
}

print "Downloading files for $tag\n";

-x $WGET || die "Can't find wget - install it and try again\n";

sub webget($$)
{
    my ($src, $dest) = @_;

    print "Get $src -> $dest\n";
    system ("cd $dest ; $WGET $src") != 0 && die "Failed fetch";
}

$files{ 'binutils-2.13.2.1.tar.bz2' } = 'support';
$files{ 'gcc-3.2.2.tar.bz2' } = 'support';

if ($tag =~ m/OOO/) {
    $files{ 'j2sdk-1.3.1-FCS-linux-i386.tar.bz2' } = 'OOO_1_0_3';
} else {
    $files{ 'j2sdk-1.4.1-01-linux-i586-gcc3.2.tar.bz2' } = 'support';
}

$files{ "$tag.tar.bz2" } = $tag;

for $a (keys %files) {
    if (-f "src/$a") {
	print "Skipping $a\n";
    } else {
	print "No file src/$a\n";
	webget("$SRC_URL/".$files{$a}."/$a", 'src');
    }
}
print "Done\n";
