#ifndef __com_sun_star_vba_CellRange_idl__
#define __com_sun_star_vba_CellRange_idl__

#ifndef __com_sun_star_vba_CellProperties_idl__
#include <com/sun/star/vba/CellProperties.idl>
#endif

#ifndef __com_sun_star_vba_XCellRange_idl__
#include <com/sun/star/vba/XCellRange.idl>
#endif

//=============================================================================

module com {  module sun {  module star {  module vba {

//=============================================================================

/** represents a range of of cells within a table.
 */
published service VBACellRange
{
	//-------------------------------------------------------------------------

	/** contains the properties of the cells of this cell range. ; 

		should we have the existing table::CellProperties service or have a property set based on
		vba model? 
  	 */
	service com::sun::star::vba::CellProperties;

	//-------------------------------------------------------------------------

	/** provides access to the cells or to sub-ranges of this cell range.
	 */
	interface com::sun::star::vba::XCellRange;

};

//=============================================================================

}; }; }; };

#endif

