#ifndef __com_sun_star_table_XWorkBook_idl__
#define __com_sun_star_table_XWorkBook_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

/*
#ifndef __com_sun_star_table_XCell_idl__
#include <com/sun/star/table/XCell.idl>
#endif
*/
//=============================================================================

module com {  module sun {  module star {  module vba {

//=============================================================================

/** 
 */
published interface XWorkBook: com::sun::star::uno::XInterface
{

	//-----------------------------------------------------------

	/** Returns the ActiveWorkBook.

		@returns
			the active work book.

		@see com::sun::star::table::CellRange
	 */
	com::sun::star::vba::XWorkBook getActiveWorkBook();

	//-----------------------------------------------------------
	/** @returns 
            the ActiveSheet object. 
		 
        @see com::sun::star::vba::XWorkSheet
	 */
	com::sun::star::vba::XWorkSheet getActiveSheet();

	//-----------------------------------------------------------
	/** @returns 
            the ActiveCell object. 
		 
        @see com::sun::star::vba::Xcell
	 */

	// make use  of already existing XCell interface or have a new one under com::sun::star::vba ? ?
	com::sun::star::vba::XCell getActiveCell();

	string getPath();

	string getName();

};

//=============================================================================

}; }; }; };

#endif
