#ifndef __org_openoffice_excel_XChart_idl__
#define __org_openoffice_excel_XChart_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif
#ifndef __org_openoffice_vba_XHelperInterface_idl__
#include <org/openoffice/vba/XHelperInterface.idl>
#endif

#ifndef __com_sun_star_helper_constantscript_BasicErrorException_idl__
#include <com/sun/star/script/BasicErrorException.idl>
#endif
//=============================================================================

module org {  module openoffice {  module excel { 

//=============================================================================
interface XRange; 
interface XChart
{
	interface ::org::openoffice::vba::XHelperInterface;
	
	[attribute, readonly] string Name;
	any SeriesCollection( [in] any Item );
	long getChartType() raises(com::sun::star::script::BasicErrorException);

	void setChartType([in] long chartType) raises(com::sun::star::script::BasicErrorException);

	void Activate() raises(com::sun::star::script::BasicErrorException);
	void setSourceData([in] XRange range, [in] any PlotBy) raises(com::sun::star::script::BasicErrorException);

	long Location() raises (com::sun::star::script::BasicErrorException);
	long getLocation() raises (com::sun::star::script::BasicErrorException);

	void setLocation([in] long where, [in] any Name) raises (com::sun::star::script::BasicErrorException);

	boolean getHasTitle() raises(com::sun::star::script::BasicErrorException);

	void setHasTitle([in] boolean bTitle) raises(com::sun::star::script::BasicErrorException);

	boolean getHasLegend() raises(com::sun::star::script::BasicErrorException);

	void setHasLegend([in] boolean bLegend) raises(com::sun::star::script::BasicErrorException);
	//XChartTitle getChartTitle() raises (com::sun::star::script::BasicErrorException);
	void setPlotBy([in] long xlRowCol) raises(com::sun::star::script::BasicErrorException);

	long getPlotBy() raises(com::sun::star::script::BasicErrorException);

	//XAxes Axes() raises (com::sun::star::script::BasicErrorException);

};

//=============================================================================

}; }; };

#endif


