#ifndef __org_openoffice_excel_XDialog_idl__
#define __org_openoffice_excel_XDialog_idl__
                                                                                                                             
#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

#ifndef __org_openoffice_vba_XHelperInterface_idl__
#include <org/openoffice/vba/XHelperInterface.idl>
#endif


//=============================================================================
                                                                                                                             
module org {  module openoffice {  module excel {
                                                                                                                             
//=============================================================================

interface XApplication;
                                                                                                                             
interface XDialog 
{
	interface ::org::openoffice::vba::XHelperInterface;

	void Show();
};
                                                                                                                             
}; }; };
                                                                                                                             
#endif

