#ifndef __org_openoffice_excel_XlAxisGroup_idl__
#define __org_openoffice_excel_XlAxisGroup_idl__
module org  { module openoffice { module excel {

constants XlAxisGroup
{
        const short xlPrimary = 1;
        const short xlSecondary = 2;
};
}; }; };
#endif
