#ifndef __org_openoffice_excel_XlAxisType_idl__
#define __org_openoffice_excel_XlAxisType_idl__
module org  { module openoffice { module excel {

constants XlAxisType
{
        const short xlCategory = 1;
        const short xlSeriesAxis = 3;
        const short xlValue = 2;
};
}; }; };
#endif
