#ifndef __org_openoffice_excel_XlCommandUnderlines_idl__
#define __org_openoffice_excel_XlCommandUnderlines_idl__
module org  { module openoffice { module excel {

constants XlCommandUnderlines
{
        const long xlCommandUnderlinesAutomatic = -4105; //(&HFFFFEFF7)
        const long xlCommandUnderlinesOff = -4146; //(&HFFFFEFCE)
        const long xlCommandUnderlinesOn = 1;
};
}; }; };
#endif
