#ifndef __org_openoffice_excel_XlCubeFieldType_idl__
#define __org_openoffice_excel_XlCubeFieldType_idl__
module org  { module openoffice { module excel {

constants XlCubeFieldType
{
        const short xlHierarchy = 1;
        const short xlMeasure = 2;
        const short xlSet = 3; 
};
}; }; };
#endif
