#ifndef __org_openoffice_excel_XlDataLabelSeparator_idl__
#define __org_openoffice_excel_XlDataLabelSeparator_idl__
module org  { module openoffice { module excel {

constants XlDataLabelSeparator
{
        const short xlDataLabelSeparatorDefault = 1;
};
}; }; };
#endif
