#ifndef __org_openoffice_excel_XlEndStyleCap_idl__
#define __org_openoffice_excel_XlEndStyleCap_idl__
module org  { module openoffice { module excel {

constants XlEndStyleCap
{
        const short xlCap = 1;
        const short xlNoCap = 2;
};
}; }; };
#endif
