#ifndef __org_openoffice_excel_XlEnableSelection_idl__
#define __org_openoffice_excel_XlEnableSelection_idl__
module org  { module openoffice { module excel {

constants XlEnableSelection
{
        const short xlNoRestrictions = 0;
        const short xlNoSelection = -4142; //(&HFFFFEFD2)
        const short xlUnlockedCells = 1;
};
}; }; };
#endif
