#ifndef __org_openoffice_excel_XlMailSystem_idl__
#define __org_openoffice_excel_XlMailSystem_idl__
module org  { module openoffice { module excel {

constants XlMailSystem
{
        const short xlMAPI = 1;
        const short xlNoMailSystem = 0;
        const short xlPowerTalk = 2;
};
}; }; };
#endif
