#ifndef __org_openoffice_excel_XlMousePointer_idl__
#define __org_openoffice_excel_XlMousePointer_idl__
module org  { module openoffice { module excel {

constants XlMousePointer
{
        const long xlDefault = -4143; //(&HFFFFEFD1)
        const long xlIBeam = 3;
        const long xlNorthwestArrow = 1;
        const long xlWait = 2;
};
}; }; };
#endif
