#ifndef __org_openoffice_excel_XlOLEVerb_idl__
#define __org_openoffice_excel_XlOLEVerb_idl__
module org  { module openoffice { module excel {

constants XlOLEVerb
{
        const short XlVerbOpen = 2;
        const short XlVerbPrimary = 1;
};
}; }; };
#endif
