#ifndef __org_openoffice_excel_XlOLEType_idl__
#define __org_openoffice_excel_XlOLEType_idl__
module org  { module openoffice { module excel {

constants XlOLEType
{
        const short XlOLEControl = 2;
        const short XlOLEEmbed = 1;
        const short XlOLELink = 0;
};
}; }; };
#endif
