#ifndef __org_openoffice_excel_XlPageBreakExtent_idl__
#define __org_openoffice_excel_XlPageBreakExtent_idl__
module org  { module openoffice { module excel {

constants XlPageBreakExtent
{
        const short xlPageBreakFull = 1;
        const short xlPageBreakPartial = 2;
};
}; }; };
#endif
