#ifndef __org_openoffice_excel_XlRangeValueDataType_idl__
#define __org_openoffice_excel_XlRangeValueDataType_idl__
module org  { module openoffice { module excel {

constants XlRangeValueDataType
{
        const short xlRangeValueDefault = 10; 
        const short xlRangeValueMSPersistXML = 12;
        const short xlRangeValueXMLSpreadsheet = 11;
};
}; }; };
#endif
