#ifndef __org_openoffice_excel_XlReferenceType_idl__
#define __org_openoffice_excel_XlReferenceType_idl__
module org  { module openoffice { module excel {

constants XlReferenceType
{
        const short xlAbsolute = 1;
        const short xlAbsRowRelColumn = 2;
        const short xlRelative = 4;
        const short xlRelRowAbsColumn = 3;
};
}; }; };
#endif
