#ifndef __org_openoffice_excel_XlSizeRepresents_idl__
#define __org_openoffice_excel_XlSizeRepresents_idl__
module org  { module openoffice { module excel {

constants XlSizeRepresents
{
        const short xlSizeIsArea = 1;
        const short xlSizeIsWidth = 2;
};
}; }; };
#endif
