#ifndef __org_openoffice_excel_XlSmartTagDisplayMode_idl__
#define __org_openoffice_excel_XlSmartTagDisplayMode_idl__
module org  { module openoffice { module excel {

constants XlSmartTagDisplayMode
{
        const short xlButtonOnly = 2;
        const short xlDisplayNone = 1;
        const short xlIndicatorAndButton = 0;
};
}; }; };
#endif
