#ifndef __org_openoffice_excel_XlSortMethod_idl__
#define __org_openoffice_excel_XlSortMethod_idl__
module org  { module openoffice { module excel {

constants XlSortMethod
{
        const short xlPinYin = 1;
        const short xlStroke = 2;
};
}; }; };
#endif
