#ifndef __org_openoffice_excel_XlSummaryReportType_idl__
#define __org_openoffice_excel_XlSummaryReportType_idl__
module org  { module openoffice { module excel {

constants XlSummaryReportType
{
        const short xlStandardSummary = 1;
        const short xlSummaryPivotTable = -4148; //(&HFFFFEFCC)
};
}; }; };
#endif
