#ifndef __org_openoffice_excel_XlSubtototalLocationType_idl__
#define __org_openoffice_excel_XlSubtototalLocationType_idl__
module org  { module openoffice { module excel {

constants XlSubtototalLocationType
{
        const short xlAtBottom = 2;
        const short xlAtTop = 1;
};
}; }; };
#endif
