#ifndef __org_openoffice_excel_XlTextVisualLayoutType_idl__
#define __org_openoffice_excel_XlTextVisualLayoutType_idl__
module org  { module openoffice { module excel {

constants XlTextVisualLayoutType
{
        const short xlTextVisualLTR = 1;
        const short xlTextVisualRTL = 2;
};
}; }; };
#endif
