#ifndef __org_openoffice_excel_XlWebSectionType_idl__
#define __org_openoffice_excel_XlWebSectionType_idl__

module org  { module openoffice { module excel {
constants XlWebSectionType
{
        const short xlAllTables = 2;
        const short xlEntirePage = 1;
        const short xlSpecifiedTables = 3;
};
}; }; };
#endif
