#ifndef __org_openoffice_excel_XlXmlLoadOption_idl__
#define __org_openoffice_excel_XlXmlLoadOption_idl__
module org  { module openoffice { module excel {
constants XlXmlLoadOption
{
        const short xlXmlLoadImportToList = 2;
        const short xlXmlLoadMapXml = 3;
        const short xlXmlLoadOpenXml = 1;
        const short xlXmlLoadPromptUser = 0;
};
}; }; };
#endif
