#ifndef __org_openoffice_excel_XlXmlImportResult_idl__
#define __org_openoffice_excel_XlXmlImportResult_idl__
module org  { module openoffice { module excel {
constants XlXmlImportResult
{
        const short xlXmlImportElementsTruncated = 1;
        const short xlXmlImportSuccess = 0;
        const short xlXmlImportValidationFailed = 2;
};
}; }; };
#endif
