module MSForms
{
    struct ReturnBoolean
    {
        boolean Value;
    };
                                                                                
    struct ReturnEffect
    {
        //fmDropEffect Value;
        short Value;
    };
                                                                                
    struct ReturnInteger
    {
        long Value;
    };
                                                                                
    struct ReturnSingle
    {
        float Value;
    };
                                                                                

};
