#ifndef __org_openoffice_vba_XDialog_idl__
#define __org_openoffice_vba_XDialog_idl__
                                                                                                                             
#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif
                                                                                                                             
                                                                                                                             
//=============================================================================
                                                                                                                             
module org {  module openoffice {  module vba {
                                                                                                                             
//=============================================================================

published interface XApplication;
                                                                                                                             
published interface XDialog : com::sun::star::uno::XInterface  
{
	[attribute, readonly] XApplication Application;
	[attribute, readonly] any Parent;
	[attribute, readonly] long Creator;
	void Show();
};
                                                                                                                             
}; }; };
                                                                                                                             
#endif

