#ifndef __org_openoffice_vba_XFont_idl__
#define __org_openoffice_vba_Font_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif
#ifndef __com_sun_star_lang_IndexOutOfBoundsException_idl__
#include <com/sun/star/lang/IndexOutOfBoundsException.idl>
#endif


//=============================================================================

module org {  module openoffice {  module vba { 

published interface XFont: com::sun::star::uno::XInterface
{
	[attribute] boolean Bold;
	[attribute] boolean Underline;
	[attribute] boolean Strikethrough;
	[attribute] boolean Shadow;
	[attribute] boolean Italic;
	[attribute] string  Name;
};

//=============================================================================

}; }; };

#endif


