#ifndef __org_openoffice_vba_XGlobals_idl__
#define __org_openoffice_vba_XGlobals_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

module org {  module openoffice {  module vba { 

published interface XApplication;
published interface XWorkbook;
published interface XWorksheet;
published interface XWorksheets;
published interface XWorkbooks;

published interface XGlobals: com::sun::star::uno::XInterface
{
        // FIXME, need better way to expose globals
	sequence< any > getGlobals();

	[attribute, readonly] org::openoffice::vba::XApplication Application;
	[attribute, readonly] org::openoffice::vba::XWorkbook ActiveWorkbook;
	[attribute, readonly] org::openoffice::vba::XWorksheet ActiveSheet;
	[attribute, readonly] org::openoffice::vba::XWorksheets WorkSheets;
	[attribute, readonly] org::openoffice::vba::XWorkbooks WorkBooks;
};

}; }; };

#endif


