#ifndef __org_openoffice_vba_XListBox_idl__
#define __org_openoffice_vba_XListBox_idl__

#ifndef __org_openoffice_vba_XControl_idl__
#include <org/openoffice/vba/XControl.idl>
#endif


//=============================================================================

module org {  module openoffice {  module vba { 


//=============================================================================
//interface XListBox: XControl 
interface XListBox: com::sun::star::uno::XInterface 
{
	[attribute] any Value;
	[attribute] string Text;
	[attribute] boolean MultiSelect;
	//[attribute] sequence< boolean > Selected;
	void AddItem( [in] any pvargItem, [in] any pvargIndex );
	void Clear();
    any Selected( [in] long index );
};

//=============================================================================

}; }; };

#endif


