#ifndef __org_openoffice_vba_XlPasteType_idl__
#define __org_openoffice_vba_XlPasteType_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

//=============================================================================

module org {  module openoffice {  module vba {

//=============================================================================

published constants xlPasteType
{
	const unsigned short xlPasteAll = 0 ;
	const unsigned short xlAll = 1;
	const unsigned short xlPasteAllExceptBorders = 2;
	const unsigned short xlPasteColumnWidths = 3;
	const unsigned short xlPasteComments = 4;
	const unsigned short xlPasteFormats = 5;
	const unsigned short xlPasteFormulas = 6;
	const unsigned short xlPasteFormulasAndNumberFormats = 7;
	const unsigned short xlPasteValidation = 8;
	const unsigned short xlPasteValues = 9 ;
	const unsigned short xlPasteValuesAndNumberFormats =10;
};

//=============================================================================

}; }; };

#endif

