#ifndef __org_openoffice_vba_XRadioButton_idl__
#define __org_openoffice_vba_XRadioButton_idl__

#ifndef __org_openoffice_vba_XControl_idl__
#include <org/openoffice/vba/XControl.idl>
#endif


//=============================================================================

module org {  module openoffice {  module vba { 

//=============================================================================
interface XRadioButton: com::sun::star::uno::XInterface 
{
	[attribute] string Caption;
	[attribute] boolean Value;
};

//=============================================================================

}; }; };

#endif


