#ifndef __org_openoffice_vba_XRange_idl__
#define __org_openoffice_vba_Range_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif
#ifndef __com_sun_star_lang_IndexOutOfBoundsException_idl__
#include <com/sun/star/lang/IndexOutOfBoundsException.idl>
#endif


//=============================================================================

module org {  module openoffice {  module vba { 

published interface XRange: com::sun::star::uno::XInterface
{
	[attribute] double Value;
	[attribute] string Formula;
	[attribute, readonly] double Count;
	[attribute, readonly] long Row;
	[attribute, readonly] long Column;
	[attribute] string Text;
	[attribute] string FormulaArray;

	void Clear();
	void ClearComments();
	void ClearContents();
	void ClearFormats();
	boolean HasFormula();
	void FillLeft();
	void FillRight();
	void FillUp();
	void FillDown();
	XRange Offset([in] any nRowOffset, [in] any nColOffset);
	XRange CurrentRegion();
	XRange CurrentArray(); 
};

//=============================================================================

}; }; };

#endif


