#ifndef __org_openoffice_vba_XTextBox_idl__
#define __org_openoffice_vba_XTextBox_idl__

#ifndef __org_openoffice_vba_XControl_idl__
#include <org/openoffice/vba/XControl.idl>
#endif

//=============================================================================

module org {  module openoffice {  module vba { 

//=============================================================================
interface XTextBox: com::sun::star::uno::XInterface 
{
	[attribute] string  Text;
//    [attribute] any    Value;
    [attribute] long    MaxLength;
    [attribute] boolean Multiline;
};

//=============================================================================

}; }; };

#endif


