#ifndef __org_openoffice_vba_XVBAToOOEventDescGen_idl__
#define __org_openoffice_vba_XVBAToOOEventDescGen_idl__

#ifndef __com_sun_star_script_ScriptEventDescriptor_idl__
#include <com/sun/star/script/ScriptEventDescriptor.idl>
#endif 

#ifndef __com_sun_star_script_XScriptEventsSupplier_idl__
#include <com/sun/star/script/XScriptEventsSupplier.idl>
#endif 

#ifndef __com_sun_star_awt_XControl_idl__
#include <com/sun/star/awt/XControl.idl>
#endif 

module org {  module openoffice {  module vba { 
interface XVBAToOOEventDescGen : com::sun::star::uno::XInterface
{
	sequence< com::sun::star::script::ScriptEventDescriptor >  getEventDescriptions( [in] com::sun::star::awt::XControl xControl );
	com::sun::star::script::XScriptEventsSupplier getEventSupplier( [in] com::sun::star::awt::XControl xControl );
};

}; }; };
#endif
