#ifndef __org_openoffice_vba_XWorksheets_idl__
#define __org_openoffice_vba_XWorksheets_idl__
                                                                                                                             
#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif
                                                                                                                             
#ifndef __org_openoffice_vba_XCollection_idl__
#include <org/openoffice/vba/XCollection.idl>
#endif
                                                                                                                             
//=============================================================================
                                                                                                                             
module org {  module openoffice {  module vba {
                                                                                                                             
//=============================================================================
                                                                                                                             
published interface XWorksheets : ::org::openoffice::vba::XCollection
{
        any  Add( [in] any Before, [in] any After, [in] any Count, [in] any Type );
                                                                                                                             
        void Copy( [in] any Before, [in] any After );
        void Move( [in] any Before, [in] any After );
        void Delete();
};
                                                                                                                             
}; }; };
                                                                                                                             
#endif

