#ifndef __org_openoffice_vba_XWorksheet_idl__
#define __org_openoffice_vba_XWorksheet_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

//=============================================================================

module org {  module openoffice {  module vba { 

//=============================================================================

published interface XRange;
published interface XWorksheet: com::sun::star::uno::XInterface
{
	[attribute, readonly] string Name;
	[attribute] boolean Visible; 
	void Activate();

	XRange Range([in] any range);
};

//=============================================================================

}; }; };

#endif


