#ifndef __org_openoffice_vba_XWorkbook_idl__
#define __org_openoffice_vba_XWorkbook_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

#include <org/openoffice/vba/OptionalAny.idl>

//=============================================================================

module org {  module openoffice {  module vba { 

//=============================================================================

published interface XWorksheet;

published interface XWorkbook: com::sun::star::uno::XInterface
{
	[attribute, readonly] string  Name;
	[attribute, readonly] string  Path;
	[attribute, readonly] string  FullName;
	[attribute, readonly] boolean ProtectStructure; 
	[attribute, readonly] XWorksheet ActiveSheet;

	void close([in] OptionalAny bSaveChanges, [in] OptionalAny aFileName, [in] OptionalAny bRouteWorkBook);
	void protect();
};

}; }; };

#endif
