#ifndef __org_openoffice_vba_XWorksheet_idl__
#define __org_openoffice_vba_XWorksheet_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

//=============================================================================

module org {  module openoffice {  module vba { 

//=============================================================================

published interface XRange;
published interface XWorksheet: com::sun::star::uno::XInterface
{
	[attribute, readonly] string Name;
	[attribute] boolean Visible; 
	[attribute, readonly] long StandardHeight;
	[attribute, readonly] long StandardWidth;
	[attribute, readonly] boolean ProtectionMode;
	[attribute, readonly] boolean ProtectContents;
	[attribute, readonly] boolean ProtectDrawingObjects;
	[attribute, readonly] XRange UsedRange; 


	
	void Activate();
	void Calculate( );
	void Move([in] any before,[in] any after );
	void Copy([in] any before,[in] any after );
	void Paste([in] any Destination,[in] any Link);
	void Delete( );
	void Protect([in] any Password,[in] any DrawingObjects ,[in] any Contents,[in] any Scenarios,[in] any UserInterfaceOnly);
	void Unprotect([in] any Password );

	XRange Range([in] any range);

};

//=============================================================================

}; }; };

#endif


