#ifndef __org_openoffice_office_MsoArrowheadWidth_idl__
#define __org_openoffice_office_MsoArrowheadWidth_idl__

module org{ module openoffice { module office {

constants MsoArrowheadWidth
{
    const long msoArrowheadNarrow = 1;
    const long msoArrowheadWide = 3;
    const long msoArrowheadWidthMedium = 2;
    const long msoArrowheadWidthMixed = -2;
};

};};};

#endif
