#ifndef __org_openoffice_coooder_xprogresslistener_idl__
#define __org_openoffice_coooder_xprogresslistener_idl__

module org { module openoffice { module coooder { 	

	interface XProgressListener {
		void updateProgress([in] long percent);
	};

 }; }; };
#endif
