#ifndef __org_openoffice_VBA_VbMsgBoxStyle_idl__
#define __org_openoffice_VBA_VbMsgBoxStyle_idl__
module org  { module openoffice { module VBA {

constants VbMsgBoxStyle
{
	const short vbYesNoCancel = 3;
	const short vbYesNo = 4;
	const short vbOKCancel = 1;
	const short vbOKOnly = 0;
};

}; }; };
#endif
