#!/bin/sh

soffice_link=`which soffice`
soffice_path=`readlink -f $soffice_link`
ooo_program_dir=$(dirname $soffice_path)


# FIXME: It does not work using the LD_LIBRARY_PATH
#        We have chnage directory to $ooo_program_dir"
# export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$ooo_program_dir"

sample_dir=`pwd`
echo cd $ooo_program_dir
cd $ooo_program_dir
echo mono $sample_dir/SpreadsheetSample.exe
mono $sample_dir/SpreadsheetSample.exe
cd -
