#!/bin/sh

if test "z$1" == "z"; then
    echo "Syntax package <version>";
    echo "  generates an ooo-fonts package";
    exit 1;
fi
NAME="ooo-fonts-$1"
echo "Creating package ooo-fonts-$1";
mkdir -p $NAME || exit 1;
cp opens___.ttf $NAME || exit 1;
tar czf $NAME.tar.gz $NAME || exit 1;
rm -Rf $NAME
echo "Done: pkg $NAME.tar.gz"
