#ifndef __org_openoffice_vba_Excel_VBA_idl__
#define __org_openoffice_vba_Excel_VBA_idl__
module org  { module openoffice { module VBA {

constants VbMsgBoxResult
{
	const short vbAbort = 3;
	const short vbCancel = 2;
	const short vbIgnore = 5;
	const short vbNo = 7;
	const short vbOK = 1;
	const short vbRetry = 4;
	const short vbYes = 6;
};

}; }; };
#endif
