#ifndef __org_openoffice_vba_XCollection_idl__
#define __org_openoffice_vba_XCollection_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif
#ifndef __org_openoffice_excel_XApplication_idl__
#include <org/openoffice/excel/XApplication.idl>
#endif
//=============================================================================

module org {  module openoffice {  module vba { 

//=============================================================================

interface XCollection : ::com::sun::star::uno::XInterface
{
	[attribute, readonly] long Count;
	[attribute, readonly] any   Parent;
	[attribute, readonly] long Creator;
	[attribute, readonly] org::openoffice::excel::XApplication Application;

	any  Item( [in] any Index );
};

}; }; };

#endif
