#ifndef __org_openoffice_msforms_XShape_idl__
#define __org_openoffice_msforms_XShape_idl__

#ifndef __org_openoffice_vba_XHelperInterface_idl__
#include <org/openoffice/vba/XHelperInterface.idl>
#endif

module org { module openoffice { module msform {
interface XShape : org::openoffice::vba::XHelperInterface
{
    [attribute] string Name;
};
}; }; };

#endif//__org_openoffice_msforms_XShape_idl__
