#ifndef __org_openoffice_msforms_XShapes_idl__
#define __org_openoffice_msforms_XShapes_idl__

#ifndef __org_openoffice_vba_XHelperInterface_idl__
#include <org/openoffice/vba/XHelperInterface.idl>
#endif

module org { module openoffice { module msform {

interface XShapeRange;
interface XShape;

interface XShapes : org::openoffice::vba::XHelperInterface
{
    long Count();
    //return a XShape
    any Item( [in] any NameOrIndex );
    void SelectAll();
    XShapeRange Range( [in] any shapes );
};
}; }; };


#endif//__org_openoffice_msforms_XShapes_idl__
