#ifndef __org_openoffice_msforms_XShapeRange_idl__
#define __org_openoffice_msforms_XShapeRange_idl__

#ifndef __org_openoffice_vba_XHelperInterface_idl__
#include <org/openoffice/vba/XHelperInterface.idl>
#endif

#ifndef __org_openoffice_msforms_XShape_idl__
#include <org/openoffice/msforms/XShape.idl>
#endif

#ifndef __org_openoffice_msforms_XShapes_idl__
#include <org/openoffice/msforms/XShapes.idl>
#endif

module org { module openoffice { module msform {

interface XShapeRange : org::openoffice::vba::XHelperInterface
{
    void Select();
    XShape Group();
    long Count();
};
}; }; };

#endif//__org_openoffice_msforms_XShapeRange_idl__
