#ifndef __org_openoffice_msforms_XShape_idl__
#define __org_openoffice_msforms_XShape_idl__

#ifndef __org_openoffice_vba_XHelperInterface_idl__
#include <org/openoffice/vba/XHelperInterface.idl>
#endif

#ifndef __org_openoffice_excel_XTextFrame_idl__
#include <org/openoffice/excel/XTextFrame.idl>
#endif

module org { module openoffice { module msform {
interface XShape : org::openoffice::vba::XHelperInterface
{
    [attribute] string Name;
    [attribute] double Height;
    [attribute] double Width;
    [attribute] double Left;
    [attribute] double Top;
    [attribute] boolean Visible;
    [attribute, readonly] long ZOrderPosition;
    org::openoffice::excel::XTextFrame TextFrame();
    void Delete();
    void ZOrder( [in] long ZOrderCmd );
};
}; }; };

#endif//__org_openoffice_msforms_XShape_idl__
