#!/usr/bin/perl -w

my $output = 'go-oo-team.png';
my $source = shift @ARGV || die "pass source file";

my %people;

my $sf;
open ($sf, $source) || die "Can't open $source: $!";
while (<$sf>) {
    /^#.*/ && next;
    /^\s*$/ && next;
    /\s*([^:]*)\s*:\s*(\S*)/ || next;
    $people{$1} = $2;
}
close ($sf);

my $montage = '';
my $text = '';
for my $name ( sort keys %people ) {
    print "Name '$name'\n";
    my $firstname = $name;
    $firstname =~ s/ .*//;
    $text .= ", " if ($text ne '');
    $text .= "$firstname";
    $montage .= "'$people{$name}' ";
}

`montage -geometry +4+4 $montage $output` && die "Montage failed";

print "update go-oo-team.diff with:\n";
print "TEXT = \"Left to right, from top: $text.\\n\";\n";
`eog $output`;

