#!/bin/sh

# sample settings
# host=storm.suse.cz
# distro=x86_64
# status_file="--status-file=../build.4.stat"
# rebuild="--rebuild"
# min=--min
# common_flags="--force"

usage()
{
    echo "This script builds OOo-devel and OOo-i18n using abuild in one call"
    
    echo "Usage: ooo-build-all --host=<host> --distro=<distro> [--min] ..."
    echo 
    echo "FIXME: Try ooo-build-package --help to get list of all options ;-)"
    
}

if test "z$1" = "z--help" ; then
    usage
    exit 1;
fi

if test -f OpenOffice_org-bootstrap.spec ; then
    bootstrap_spec=OpenOffice_org-bootstrap.spec
    bootstrap_devel_packages=OpenOffice_org-bootstrap
else
    bootstrap_spec=OpenOffice_org.spec
    bootstrap_devel_packages=OpenOffice_org-devel
fi

# typical common 
common_options="$@
    --get-packages=/prace/RPMS"

# bootstrap settings
bootstrap_options="$common_options
    --keep-remote-tempdir"

if test -f OpenOffice_org-i18n.spec -o \
        -f OpenOffice_org-i18n-group1.spec -o \
        -f OpenOffice_org-l10n-group1.spec -o \
        -f OpenOffice_org-bootstrap.spec ; then
    bootstrap_options="$bootstrap_options
	--no-final-message"
fi

bootstrap_status_file=`ooo-build-package $bootstrap_options --get-status-file $bootstrap_spec | tail -n 1`

if test -z "$bootstrap_status_file" ; then
    echo "Error: Was not able to get status file for devel build"
    exit 1;
fi

other_options="--keep-remote-tempdir
    --prefer-rpms-from-build=$bootstrap_status_file
    --re-use-remote-prefer-rpms-from-build=$bootstrap_status_file
    --re-use-remote-sources-from-build=$bootstrap_status_file
    --do-not-update-remote-sources
    --keep-remote-tempdir"

default_options="$common_options $other_options"

l10n_group1_options="$common_options $other_options
    --devel-packages=OpenOffice_org-l10n-en-US"

ooo-build-package $bootstrap_options --devel-packages="$bootstrap_devel_packages" $bootstrap_spec || exit 1;

if test -f OpenOffice_org-ure.spec ; then ooo-build-package $default_options --no-final-message --devel-packages="OpenOffice_org-ure,OpenOffice_org-ure-devel" OpenOffice_org-ure.spec || exit 1; fi
if test -f OpenOffice_org-artwork.spec ; then ooo-build-package $default_options --no-final-message --devel-packages="OpenOffice_org-artwork-devel" OpenOffice_org-artwork.spec || exit 1; fi
if test -f OpenOffice_org-libs-extern.spec ; then ooo-build-package $default_options --no-final-message --devel-packages="OpenOffice_org-libs-extern,OpenOffice_org-libs-extern-devel" OpenOffice_org-libs-extern.spec || exit 1; fi
if test -f OpenOffice_org-libs-gui.spec ; then ooo-build-package $default_options --no-final-message --devel-packages="OpenOffice_org-libs-gui,OpenOffice_org-libs-gui-devel" OpenOffice_org-libs-gui.spec || exit 1; fi
if test -f OpenOffice_org-libs-core.spec ; then ooo-build-package $default_options --no-final-message --devel-packages="OpenOffice_org-libs-core,OpenOffice_org-libs-core-devel" OpenOffice_org-libs-core.spec || exit 1; fi
if test -f OpenOffice_org-components.spec ; then ooo-build-package $default_options --no-final-message --devel-packages="OpenOffice_org-components,OpenOffice_org-components-devel" OpenOffice_org-components.spec || exit 1; fi
if test -f OpenOffice_org-l10n.spec ; then ooo-build-package $default_options --no-final-message --devel-packages="OpenOffice_org-l10n,OpenOffice_org-l10n-devel" OpenOffice_org-l10n.spec || exit 1; fi
if test -f OpenOffice_org-impress.spec ; then ooo-build-package $default_options --no-final-message --devel-packages="OpenOffice_org-impress,OpenOffice_org-impress-devel" OpenOffice_org-impress.spec || exit 1; fi
if test -f OpenOffice_org-writer.spec ; then ooo-build-package $default_options --no-final-message --devel-packages="OpenOffice_org-writer,OpenOffice_org-writer-devel" OpenOffice_org-writer.spec || exit 1; fi
if test -f OpenOffice_org-calc.spec ; then ooo-build-package $default_options --no-final-message --devel-packages="OpenOffice_org-calc,OpenOffice_org-calc-devel" OpenOffice_org-calc.spec || exit 1; fi
if test -f OpenOffice_org-base.spec ; then ooo-build-package $default_options --no-final-message --devel-packages="OpenOffice_org-base,OpenOffice_org-base-devel" OpenOffice_org-base.spec || exit 1; fi
if test -f OpenOffice_org-filters.spec ; then ooo-build-package $default_options --no-final-message --devel-packages="OpenOffice_org-filters,OpenOffice_org-filters-devel" OpenOffice_org-filters.spec || exit 1; fi

if test -f OpenOffice_org-icon-themes.spec ; then ooo-build-package $default_options --devel-packages="OpenOffice_org-icon-themes" OpenOffice_org-icon-themes.spec || exit 1; fi
if test -f OpenOffice_org-i18n.spec ; then ooo-build-package $default_options OpenOffice_org-i18n.spec || exit 1; fi
if test -f OpenOffice_org-i18n-group1.spec ; then ooo-build-package $default_options OpenOffice_org-i18n-group1.spec || exit 1; fi
if test -f OpenOffice_org-i18n-group2.spec ; then ooo-build-package $default_options OpenOffice_org-i18n-group2.spec || exit 1; fi
if test -f OpenOffice_org-l10n-group1.spec ; then ooo-build-package $l10n_group1_options OpenOffice_org-l10n-group1.spec || exit 1; fi
if test -f OpenOffice_org-l10n-group2.spec ; then ooo-build-package $default_options OpenOffice_org-l10n-group2.spec || exit 1; fi

if test -f OpenOffice_org-bootstrap.spec ; then ooo-build-package $default_options --devel-packages="OpenOffice_org" OpenOffice_org.spec || exit 1; fi


remove_options="$common_options
    --remove-remote-tempdir=$bootstrap_status_file"

ooo-build-package $remove_options || exit 1;
