#!/bin/sh

host=storm.suse.cz
distro=x86_64
status_file=../build.4.stat
min=--min
common_flags="--force"

usage()
{
    echo "This script builds OOo-devel and OOo-i18n using abuild in one call"
}

if test "z$1" = "z--help" ; then
    usage
    exit 1;
fi



ooo-build-package \
    --host=$host \
    --distro=$distro \
    $min \
    $common_flags \
    --status-file=$status_file \
    --keep-remote-tempdir  \
    --no-final-message \
    OpenOffice_org.spec || exit 1;
ooo-build-package \
    --host=$host \
    --distro=$distro \
    $min \
    $common_flags \
    --prefer-rpms-from-build=$status_file \
    --re-use-remote-sources-from-build=$status_file \
    --do-not-update-remote-sources  \
    OpenOffice_org-i18n.spec
