#!/usr/bin/perl -pi.bak

s|\$\{solar.jar\}/juh.jar|\$\{split.ure\}/share/java/juh.jar|g;
s|\$\{solar.jar\}/ridl.jar|\$\{split.ure\}/share/java/ridl.jar|g;
s|\$\{solar.jar\}/jurt.jar|\$\{split.ure\}/share/java/jurt.jar|g;

s|\$\{solar.jar\}/jaxp.jar|\$\{split.dev\}/bin/jaxp.jar|g;
s|\$\{solar.jar\}/parser.jar|\$\{split.dev\}/bin/parser.jar|g;

s|\$\{solar.jar\}/unoil.jar|\$\{split.install\}/classes/unoil.jar|g;
s|\$\{solar.jar\}/sandbox.jar|\$\{split.install\}/classes/sandbox.jar|g;
