#!/bin/bash

export ARCH=i586
export PATH="/opt/icecream/bin:$PATH"
modules="bootstrap ure libs_extern artwork libs_gui libs_core components l10n impress writer calc base filters %%"
if test "z$1" != "z"; then
   buildfrom=$1
   modules=`echo $modules | sed s/.*$buildfrom/$buildfrom/`;
   echo "Buiding from $buildfrom: $modules"
else
   echo "Straight through build"
   cd /opt/OpenOffice/HEAD
   make dist || exit 1;
fi
verstr=3-8
cd /usr/src/packages
for module in $modules; do
    if test "$module" == "%%"; then
	suffix=""
    else
	suffix="_$module"
    fi
    sudo bash -l -c "/usr/bin/rpmbuild --eval '%define jobs 10' -ba SPECS/ooo3$suffix.spec" || exit 1
    echo "Installing $module RPM(s)"
    sudo rpm -U --force RPMS/$ARCH/ooo3$suffix-$verstr.$ARCH.rpm || exit 1
    if test -f RPMS/$ARCH/ooo3$suffix-devel-$verstr.$ARCH.rpm; then
        sudo rpm -U --force RPMS/$ARCH/ooo3$suffix-devel-$verstr.$ARCH.rpm || exit 1
    fi
done
