#!/bin/bash

modules="bootstrap ure libs_extern artwork libs_gui libs_core components l10n impress writer calc base filters"
if test "z$1" != "z"; then
   buildfrom=$1
   modules=`echo $modules | sed s/.*$buildfrom/$buildfrom/`;
   echo "Buiding from $buildfrom: $modules"
else
   echo "Straight through build"
   cd /opt/OpenOffice/HEAD
   make dist || exit 1;
fi
verstr=3-8
cd /usr/src/packages
for module in $modules; do
    sudo bash -l -c "/usr/bin/rpmbuild --eval '%define jobs 8' -ba SPECS/ooo3_$module.spec" || exit 1
    echo "Installing $module RPM(s)"
    sudo rpm -U --force RPMS/i586/ooo3_$module-$verstr.i586.rpm || exit 1
    if test -f RPMS/i586/ooo3_$module-devel-$verstr.i586.rpm; then
        sudo rpm -U --force RPMS/i586/ooo3_$module-devel-$verstr.i586.rpm || exit 1
    fi
done
