#!/bin/sh
echo "Please close OOo window manually when it appears for about 2-5 seconds"
for i in $(rpm -ql $(rpm -qa | grep -i openoffice) |grep -ie /usr/bin/ -e /usr/sbin -e /usr/X11R6/bin/ |grep -i oo|grep -v convert|sort);do
echo $i
$i 
sleep 8
done

