#ifndef __org_openoffice_msforms_XColorFormat_idl__
#define __org_openoffice_msforms_XColorFormat_idl__

#ifndef __org_openoffice_vba_XHelperInterface_idl__
#include <org/openoffice/vba/XHelperInterface.idl>
#endif

module org { module openoffice { module msforms {

interface XColorFormat : org::openoffice::vba::XHelperInterface
{
    [attribute] long RGB;
    [attribute] long SchemeColor;
};

};};};
#endif
