#ifndef __org_openoffice_msforms_XPictureFormat_idl__
#define __org_openoffice_msforms_XPictureFormat_idl__


#ifndef __org_openoffice_vba_XHelperInterface_idl__
#include <org/openoffice/vba/XHelperInterface.idl>
#endif

module org { module openoffice { module msforms {
interface XPictureFormat : org::openoffice::vba::XHelperInterface
{
    [attribute] double Brightness;
    [attribute] double Contrast;
    void IncrementBrightness( [in] double increment );
    void IncrementContrast( [in] double increment );
};
}; }; };

#endif
