#ifndef __org_openoffice_coooder_ui_parsetrigger_idl__
#define __org_openoffice_coooder_ui_parsetrigger_idl__

#include <com/sun/star/task/XJobExecutor.idl>
module org { module openoffice { module coooder { module ui { 	

	service ParseTrigger : com::sun::star::task::XJobExecutor {

	};

 }; }; }; };
#endif
